---
name: scan-secret
description: scan secrets in code repository

runs:
  using: "composite"
  steps:
    - run: docker run -v "$(pwd)":"/path" zricethezav/gitleaks:latest detect -c "/path/actions/secret-scan/gitleaks.toml" -s "/path" --no-git -r "/path/docker-bind/output.json"
      shell: bash
      