---
name: dependencies scan
description: scan dependencies in code repository

runs:
  using: "composite"
  steps:
    - run: ls -la
      shell: bash
    - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json > oast-results.json
      shell: bash
    - run: mv oast-results.json docker-bind/
      shell: bash
    - run: ls -la docker-bind
      shell: bash
      