- name: Deploy API
  hosts: prod
  tasks:
  - name: create test
    ansible.builtin.shell: |       # Multiple commands in Ansible shell module
          mkdir github-test
          touch ./github-test/github.txt

  - name: Copy content of directory
    copy:
      src: $(pwd)/api.py    # note the '/' <-- !!!
      dest: /tmp/

