- name: Deploy API
  hosts: prod
  tasks:

  - name: Copy api.py
    copy:
      src: api.py    
      dest: ~/web-api/api.py

  - name: Copy requirements.txt
    copy:
      src: requirements.txt    
      dest: ~/web-api/requirements.txt

  - name: install dependencies
    ansible.builtin.shell: |       # Multiple commands in Ansible shell module
          pip3 install -r ~/web-api/requirements.txt

  # - name: run the api
  #   ansible.builtin.shell: |       # Multiple commands in Ansible shell module
  #         cd ~/web-api | flask run &

  - name: run service
    command: bash -lc "cd ~/web-api && python3 api.py"
