- name: Revoke API
  hosts: prod
  tasks:

  - name: stop the api
    ansible.builtin.shell: |       # Multiple commands in Ansible shell module
        sudo systemctl stop web-api
    ignore_errors: true

  - name: delete the files
    ansible.builtin.shell: |       # Multiple commands in Ansible shell module
        rm -rf ~/web-api/*
    ignore_errors: true