---
name: deploy-ansible
description: deploy the code to the server

inputs:

  ssh-key:
    description: private ssh key 
    required: true

  server-name:
    description: server host name
    required: true

runs:
  using: "composite"
  steps:
    - run: python3 -m pip install --user ansible
      shell: bash
    - run: ansible --version
      shell: bash
    - run: |
        mkdir -p .ssh
        echo "${{ inputs.ssh-key }}" | tr -d '\r' > .ssh/id_rsa
        chmod 600 .ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add .ssh/id_rsa
        ssh-keyscan -H ${{ inputs.server-name }} >> .ssh/known_hosts
      shell: bash
    - run: echo .ssh/id_rsa
      shell: bash
    - run: echo .ssh/known_hosts
      shell: bash
