

name: CI


on: 
  pull_request:

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Test program
        run: python -m unittest test.py
 
  security:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - run: mkdir -m 777 docker-bind

      - name: run secret scan
        id: secret
        uses: ./actions/secret-scan
        continue-on-error: true
      - run: mv docker-bind/output.json .

      - name: run dependencies scan
        id: dependencies
        uses: ./actions/dependency-scan
        continue-on-error: true

      - name: run static scan
        id: static
        uses: ./actions/static-scan
        continue-on-error: true

      - run: ls -la
      
      - name: run alert secret
        run: python3 ./actions/secret-scan/slack-alert.py ${{ secrets.SLACK_WEBHOOK}}

      - name: run alert dependencies
        run: python3 ./actions/dependency-scan/slack-alert.py ${{ secrets.SLACK_WEBHOOK}}

      # - name: check failure
      #   if: steps.secret.outcome != 'success' || steps.dependencies.outcome != 'success'
      #   run: exit 1
      # - name: check failure
      #   if: steps.dependencies.outcome != 'success'
      #   run: exit 1 # test


  # deploy:
  #   needs: security
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: run deploy
  #       uses: ./actions/deploy-ansible
  #       with:
  #         ssh-key: ${{ secrets.DEPLOYMENT_SERVER_SSH_PRIVKEY }}
  #         known-host: ${{ secrets.KNOWN_HOST }}
  #       timeout-minutes: 8
          

