name: revoke application

on: 

  workflow_dispatch:

jobs:

  revoke:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: run revoke
        uses: ./actions/revoke-ansible
        with:
          ssh-key: ${{ secrets.DEPLOYMENT_SERVER_SSH_PRIVKEY }}
          known-host: ${{ secrets.KNOWN_HOST }}\
        continue-on-error: true